### ISSUE TITLE
api 502 bad gateway

### ISSUE THREAD

**Issue by yyli** [sanghviharshit/ha-mila#6] opened 2022-06-02 00:32 UTC
```
2022-06-01 20:30:37 INFO (MainThread) [custom_components.mila.milacloud] get https://api.milacares.com/mms/appliances/meta
2022-06-01 20:30:39 INFO (MainThread) [custom_components.mila.milacloud] 502, message='Bad Gateway', url=URL('https://api.milacares.com/mms/appliances/meta')
```

**Comment by sanghviharshit** [comment] 2022-06-02 16:35
This is a duplicate of #7

**Closed as completed by sanghviharshit** 2022-06-02 16:35 UTC
Labels: duplicate
