### ISSUE TITLE
Invalid Login

### ISSUE THREAD

**Issue by marcthespot0** [sanghviharshit/ha-mila#10] opened 2022-06-16 19:52 UTC
Hello - Thank you for this great integration with my Mila! I hope I can get it working.

When I add the Mila Integration and am prompted to log in I am getting  "Invalid Login".  I know I am using the correct credentials because I can log in to the Mila app successfully.  Any thoughts?

I am getting this error under logs:
This error originated from a custom integration.
Logger: custom_components.mila.config_flow
Source: custom_components/mila/config_flow.py:73
Integration: Mila ([documentation](https://github.com/sanghviharshit/ha-mila), [issues](https://github.com/sanghviharshit/ha-mila/issues))
First occurred: 3:50:22 PM (3 occurrences)
Last logged: 3:53:23 PM

Status: 500, Error Message: Error with get https://api.milacares.com/mms/appliances/meta
Status: 500, Error Message: Error with get https://id.milacares.com/auth/realms/prod/protocol/openid-connect/auth

**Comment by sanghviharshit** [comment] 2022-06-16 20:19
Duplicate of #7

**Closed as completed by sanghviharshit** 2022-06-16 20:20 UTC
Labels: duplicate
